In [1]:
import torch

**gradient**

In [2]:
x = torch.tensor([3.0],dtype=torch.float32,requires_grad=True)
y = x**2 + 4
y.backward()  #dy/dx = 2x = 2*3 = 6
print(x.grad)

tensor([6.])


In [3]:
x = torch.tensor(3.0)               #dz/dx = y*x**(y-1) = 7*3**6 = 5103
y = torch.tensor(7.0)               #dz/dy = ?  #take log on both side
                                    #d (logx base a)/dx = 1/x * log a base e = 1/x
x.requires_grad_(True)              #log(z) = log x**y = y*log(x)
y.requires_grad_(True)              # d log(z)/dy = (log x)
                                    # (1/z)* dz/dy = log x
                                    #dz/dy = z*log x = (x**y) * log x = 3**7 * log 3 base e = 2187*1.098612 = 2402.66
z = x**y
z.backward()             #

print(x.grad)
print(y.grad)

tensor(5103.)
tensor(2402.6650)


In [4]:
m = torch.tensor(2.0,dtype=torch.float32,requires_grad=True)
x = torch.tensor(4.0,dtype=torch.float32,requires_grad=True)
c = torch.tensor(7.0,dtype=torch.float32,requires_grad=True)

x = x.detach()

y = m*x+c
y.backward()

print(m.grad)
print(x.grad)
print(c.grad)

tensor(4.)
None
tensor(1.)


**Softmax nd cross-entropy loss using numpy**

In [5]:
import numpy as np
from numpy import exp,log

In [6]:
#3 classes and 3 samples
x1,y1_actual = np.array([2.5,0.3,0.6]),np.array([1,0,0])
x2,y2_actual = np.array([0.3,2.7,0.3]),np.array([0,1,0])
x3,y3_actual = np.array([0.1,0.2,1.6]),np.array([0,0,1])

In [7]:
exp(2.5)/(exp(2.5)+exp(0.3)+exp(0.6))

0.7934166868732382

In [8]:
def softmax(x):
  return exp(x)/np.sum(exp(x))

y1_pred=softmax(x1)
y2_pred=softmax(x2)
y3_pred=softmax(x3)
print(y1_pred,y2_pred,y3_pred)

[0.79341669 0.08791307 0.11867024] [0.07678618 0.84642763 0.07678618] [0.15181741 0.16778418 0.68039841]


In [9]:
#cross-entropy loss
loss_x1 = -np.sum(y1_actual*log(y1_pred)) # -(1*log(0.79) + 0*log(0.0879) + 0*log(0.1186))
loss_x2 = -np.sum(y2_actual*log(y2_pred))
loss_x3 = -np.sum(y3_actual*log(y3_pred))
print(loss_x1,loss_x2,loss_x3)

#overall loss = mean of loss associated with each example
loss = (loss_x1+loss_x2+loss_x3)/3
print(loss)

0.23140673901665318 0.16673056867343997 0.3850767536885644
0.2610713537928859


**Using Pytorch**

In [10]:
import torch
import torch.nn as nn

#3classes and 3 samples
x = torch.tensor([[2.5,0.3,0.6],[0.3,2.7,0.3],[0.1,0.2,1.6]])
y = torch.tensor([0,1,2])

**Ex1**

In [11]:
y_pred = torch.softmax(x,dim=1) #for dim=0 it will calculate row-wise which is wrong
y_pred

tensor([[0.7934, 0.0879, 0.1187],
        [0.0768, 0.8464, 0.0768],
        [0.1518, 0.1678, 0.6804]])

**mtd1**

In [12]:
loss = -(np.log(0.7934)+np.log(0.8464)+np.log(0.6804))/3
loss

0.26108846908014655

**mtd2**

In [13]:
loss2 = torch.mean(-torch.log(y_pred.gather(1,y.view(-1,1))))
loss2

tensor(0.2611)

**mtd3**

In [14]:
criterion1 = nn.CrossEntropyLoss()
loss3 = criterion1(x,y)
loss3

tensor(0.2611)

**Ex2**

In [15]:
#5 classes and 4 samples
x = torch.tensor([[0.19,0.15,0.5,3.5,0.4],[2.5,0.01,0.02,0.15,0.29],[0.03,0.19,2.7,0.3,1.5],[0.1,1.6,0.2,0.08,0.15]])
y = torch.tensor([3,0,2,1])

In [16]:
criterion = nn.CrossEntropyLoss()
loss = criterion(x,y)
loss.item()

0.3893183171749115