In [1]:
import torch
import numpy as np

**1D -Tensor Creation**

In [2]:
tensor_1 = torch.tensor([1,2,3])
print(tensor_1)

tensor([1, 2, 3])


In [3]:
empty_tensor = torch.empty(3)
print(empty_tensor)

tensor([1.5947e-42, 3.0742e-41, 1.1958e+37])


In [4]:
zero_tensor = torch.zeros(2,3)
print(zero_tensor)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [5]:
one_tensor = torch.ones(3,2)
print(one_tensor)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [6]:
#arange(start_value,end_value,step_size)
#default s_value=0, step_size=1
arange_tensor = torch.arange(1,36,2.5)
print(arange_tensor)

tensor([ 1.0000,  3.5000,  6.0000,  8.5000, 11.0000, 13.5000, 16.0000, 18.5000,
        21.0000, 23.5000, 26.0000, 28.5000, 31.0000, 33.5000])


In [7]:
#linspace(s_value,e_value,no of elements)
#it creates arrays with specific no of elements, which are equally spaced b/w begining and end value.
linsapce_tensor = torch.linspace(1,10,5)
print(linsapce_tensor)

tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])


**2D- Tensor Creation**

In [8]:
random_int_tensor = torch.randint(1,6,(2,3))
random_int_tensor

tensor([[2, 3, 3],
        [5, 3, 5]])

In [9]:
random_tensor = torch.rand(4,5)
print(random_tensor)

tensor([[0.9529, 0.8147, 0.4364, 0.2772, 0.7206],
        [0.5236, 0.8245, 0.4365, 0.0969, 0.9588],
        [0.5825, 0.9814, 0.2624, 0.9375, 0.2947],
        [0.9405, 0.3528, 0.4762, 0.3264, 0.7464]])


In [10]:
random_tensor[1,2]

tensor(0.4365)

In [11]:
random_tensor[1,2].item()

0.43652552366256714

In [12]:
random_tensor[1,:]

tensor([0.5236, 0.8245, 0.4365, 0.0969, 0.9588])

In [13]:
random_tensor[:,2]

tensor([0.4364, 0.4365, 0.2624, 0.4762])

**Reshaping**

In [14]:
reshaped_tensor = random_tensor.view(-1,2)
#or reshaped_tensor = random_tensor.view(5,2)
print("after reshaping: ",reshaped_tensor)

after reshaping:  tensor([[0.9529, 0.8147],
        [0.4364, 0.2772],
        [0.7206, 0.5236],
        [0.8245, 0.4365],
        [0.0969, 0.9588],
        [0.5825, 0.9814],
        [0.2624, 0.9375],
        [0.2947, 0.9405],
        [0.3528, 0.4762],
        [0.3264, 0.7464]])


In [15]:
reshaped_tensor.flatten()

tensor([0.9529, 0.8147, 0.4364, 0.2772, 0.7206, 0.5236, 0.8245, 0.4365, 0.0969,
        0.9588, 0.5825, 0.9814, 0.2624, 0.9375, 0.2947, 0.9405, 0.3528, 0.4762,
        0.3264, 0.7464])

**Math Operations**

In [16]:
#transpose
print(random_int_tensor)
print(random_int_tensor.T)

tensor([[2, 3, 3],
        [5, 3, 5]])
tensor([[2, 5],
        [3, 3],
        [3, 5]])


In [17]:
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])

add1= a+b
print(add1)
add2 = torch.add(a,b)
print(add2)
add3 = a.add_(b)
print(add3)


tensor([5, 7, 9])
tensor([5, 7, 9])
tensor([5, 7, 9])


In [18]:
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])

sub1 = a-b
print(sub1)
sub2 = torch.sub(a,b)
print(sub2)
sub3 = a.sub_(b)
print(sub3)

tensor([-3, -3, -3])
tensor([-3, -3, -3])
tensor([-3, -3, -3])


In [19]:
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])

mul1 = a*b
print(mul1)
mul2 = torch.mul(a,b)
print(mul2)
mul3 = a.mul_(b)
print(mul3)

tensor([ 4, 10, 18])
tensor([ 4, 10, 18])
tensor([ 4, 10, 18])


**Element wise product / Hadamard product**

In [20]:
x = torch.tensor([[1,2],[3,4]])
y = torch.tensor([[5,6],[7,8]])
mul4 = torch.mul(x,y)
print(mul4)

tensor([[ 5, 12],
        [21, 32]])


**Matrix multiplication**

In [21]:
x = torch.tensor([[1,2],[3,4]])
y = torch.tensor([[5,6],[7,8]])
mul5 = torch.mm(x,y)
print(mul5)

tensor([[19, 22],
        [43, 50]])


In [22]:
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])

div1 = a/b
print(div1)
div2 = torch.div(a,b)
print(div2)

tensor([0.2500, 0.4000, 0.5000])
tensor([0.2500, 0.4000, 0.5000])


**type vs dtype**

In [23]:
type(div2),type(mul5)

(torch.Tensor, torch.Tensor)

In [24]:
div2.dtype, mul5.dtype

(torch.float32, torch.int64)

In [25]:
tensor_int = torch.tensor([1,2,3],dtype=torch.int64)
print(type(tensor_int))
print(tensor_int.dtype)

<class 'torch.Tensor'>
torch.int64


In [26]:
tensor_float = tensor_int.to(torch.float64)
print(tensor_float)
print(type(tensor_float))
print(tensor_float.dtype)

tensor([1., 2., 3.], dtype=torch.float64)
<class 'torch.Tensor'>
torch.float64


**shapes nd sizes**

In [27]:
x = torch.tensor([[1,2],[3,4]],dtype=torch.float32)
print(x)
print(type(x))
print(x.dtype)
print(x.ndim)
print(x.size())
print(x.shape)

tensor([[1., 2.],
        [3., 4.]])
<class 'torch.Tensor'>
torch.float32
2
torch.Size([2, 2])
torch.Size([2, 2])


**Device**

In [28]:
tensor_int.device

device(type='cpu')

In [29]:
torch.cuda.is_available(), torch.cuda.device_count()

(True, 1)

In [30]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device

device(type='cuda')

In [31]:
tensor_int = tensor_int.to(device)

In [32]:
tensor_int.device

device(type='cuda', index=0)

In [33]:
tensor_new  = torch.tensor([2.5,3.2],dtype=torch.float32, device='cuda')
tensor_new

tensor([2.5000, 3.2000], device='cuda:0')

In [34]:
tensor_new.device

device(type='cuda', index=0)